### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by TSanf0rd**
# Issue #4
### Before

I addressed the issues you've pointed out, including cleaning up unnecessary comments and fixing the logo link for GDSC. I'll also refine the HTML structure by removing containers, and ensure that the links for events, Discord, and Bevy are correctly placed. Expect font color and link spacing enhancements as well. 

### After

The unnecessary comments in footer-components.html and home.component.html have been removed, and the incorrect GDSC logo link is now corrected. I've cleaned up the HTML files by deleting unnecessary containers. The links for events, Discord, and Bevy have been added and verified. Additionally, the font colors and spacing for links have been updated for better readability. Please review the changes and let me know if there's anything else that needs attention!

### CODE REVIEW

**Comment by TSanf0rd** [comment]
I put #issue #20 and its still not moving to the review folder

**Comment by reidhaegele** [comment]
Good work making the changes, however this pull request still needs work. The pull request should focus on the behavior of the website before and after. Do not include code snippets. The pull request shows all added, deleted, and modified code already. Instead, for this issue I would simply state: "Before: The website has no footer. After: The footer component is created and placed at the bottom of each page with working links".

Additionally,
> I put #issue #20 and its still not moving to the review folder

This relates to issue #4 not #20 (20 is just this pull request).

**Comment by TSanf0rd** [comment]
Ready for Review

**Review by rspering — APPROVED** [review]
Looks awesome! Love the organization in your SCSS file and I like that you went ahead and made the links functional in footer. We can easily new links later on as the website grows. Great work!

**Pull request merged**
